server {
        listen 80;
        listen [::]:80;

        server_name static.148.211.62.46.clients.your-server.de;

        return 308 https://$host$request_uri;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;

	http2 on;

	ssl_certificate /etc/letsencrypt/live/static.148.211.62.46.clients.your-server.de/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/static.148.211.62.46.clients.your-server.de/privkey.pem;
	include /etc/letsencrypt/options-ssl-nginx.conf;
	ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

	root /var/www/static.148.211.62.46.clients.your-server.de/;

	index index.html index.htm index.nginx-debian.html;

	server_name static.148.211.62.46.clients.your-server.de;

	more_clear_headers Server;
	more_set_headers 'Server: Webserver';
	add_header X-Frame-Options DENY always;
	add_header Content-Security-Policy "
		default-src 'none';
		script-src 'self' https://cdn.jsdelivr.net;
		style-src 'self' https://cdn.jsdelivr.net;
		img-src 'self' https://cdn2.thecatapi.com data:;
		connect-src 'self';
		font-src https://cdn.jsdelivr.net;
		base-uri 'self';
		form-action 'self';
	" always; 
	add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
	add_header X-Content-Type-Options nosniff always;

	location / {
		alias /var/www/static.148.211.62.46.clients.your-server.de/frontend/;
		try_files $uri $uri/ =404;
	}

	location /api/ {
        proxy_pass http://127.0.0.1:5000/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
